import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "../component/Navber";
import Footer from "../component/Footer";
import { auth } from "@/auth"
import Courses from "@/component/Courses";
import Feature from "@/component/Feature";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LiveCodeX",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navber session={session} ></Navber>
        <main className="container mx-auto min-h-[calc(100vh-405px)]">
          {children}
        </main>
         <Courses></Courses>
         <Feature></Feature>

        <Footer />
      </body>
    </html>
  );
}
