import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "../component/Navber";
import Footer from "../component/Footer";
import { auth } from "@/auth"

const geistSans = Geist({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LiveCodeX",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className}`}>
        <Navber session={session} ></Navber>
        <main className=" mx-auto min-h-[calc(100vh-405px)]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
